packages:
  - apps/*
  - packages/*

saveExact: true
engineStrict: true
strictPeerDependencies: true
packageManagerStrictVersion: true
managePackageManagerVersions: false
strictDepBuilds: true
allowBuilds: {}
